dist: bionic

language: python

notifications:
    email: false

python:
    - "3.5"
    - "3.6"
    - "3.7"

before_install:
    - sudo add-apt-repository -y ppa:mc3man/xerus-media
    - sudo apt-get update
    - sudo apt-get install -y ffmpeg
    - ffmpeg -hwaccels

install:
    - pip install -r requirements.txt
    - pip install -e .[tests]

script:
     - while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
     - py.test
     - kill %1
